In [19]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.shape

(569, 31)

In [8]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling the different type of numerical features

In [9]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
X_train

array([[ 0.44237017,  0.94702119,  0.76261789, ...,  2.03558532,
         0.65748443,  1.00048799],
       [ 0.08529951, -0.60928064,  0.09250418, ...,  0.4193027 ,
         0.28641019,  0.21407827],
       [-0.53957415,  0.76942519, -0.57426939, ..., -0.78442686,
         0.36426952, -0.09530171],
       ...,
       [ 0.40493534,  3.36793515,  0.49123227, ...,  1.34465535,
         1.04678107,  2.02072501],
       [-0.26313234,  1.42606305, -0.32709972, ..., -0.83532125,
        -0.72244791, -0.87564516],
       [-0.070199  , -0.69807864, -0.14882025, ..., -1.0617242 ,
        -0.56010293, -0.96663927]])

In [13]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [14]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,

In [16]:
y_train.shape,y_test.shape

((455,), (114,))

In [17]:
X_train.shape,X_test.shape

((455, 30), (114, 30))

Transforming the array into tensor by using from_numpy

In [20]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [21]:
X_train_tensor.shape

torch.Size([455, 30])

In [22]:
X_train_tensor


tensor([[ 0.4424,  0.9470,  0.7626,  ...,  2.0356,  0.6575,  1.0005],
        [ 0.0853, -0.6093,  0.0925,  ...,  0.4193,  0.2864,  0.2141],
        [-0.5396,  0.7694, -0.5743,  ..., -0.7844,  0.3643, -0.0953],
        ...,
        [ 0.4049,  3.3679,  0.4912,  ...,  1.3447,  1.0468,  2.0207],
        [-0.2631,  1.4261, -0.3271,  ..., -0.8353, -0.7224, -0.8756],
        [-0.0702, -0.6981, -0.1488,  ..., -1.0617, -0.5601, -0.9666]],
       dtype=torch.float64)

Defining the Model

In [28]:
class Simplenn():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
    #To caluculate loss
  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


Parameters

In [24]:
leaning_rate=0.1
epochs=25


Traning Pipeline

In [32]:
model=Simplenn(X_train_tensor)
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  #loss
  loss=model.loss_function(y_pred,y_train_tensor)
  #Backward
  loss.backward()
  #parameter update
  with torch.no_grad():
    model.weights-=leaning_rate*model.weights.grad
    model.bias-=leaning_rate*model.bias.grad
  #zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/25, Loss: 3.7353033707138263
Epoch 2/25, Loss: 3.6163881019457973
Epoch 3/25, Loss: 3.4900995367560768
Epoch 4/25, Loss: 3.3559203579323196
Epoch 5/25, Loss: 3.2186116499082402
Epoch 6/25, Loss: 3.0758487068405294
Epoch 7/25, Loss: 2.9292509904090402
Epoch 8/25, Loss: 2.7735864745150307
Epoch 9/25, Loss: 2.609625708030946
Epoch 10/25, Loss: 2.440243569911806
Epoch 11/25, Loss: 2.265930326882841
Epoch 12/25, Loss: 2.0868628286524986
Epoch 13/25, Loss: 1.9113061941832785
Epoch 14/25, Loss: 1.7437287031468072
Epoch 15/25, Loss: 1.58575211503588
Epoch 16/25, Loss: 1.434322599968506
Epoch 17/25, Loss: 1.2970666871050414
Epoch 18/25, Loss: 1.1762112579946922
Epoch 19/25, Loss: 1.0737087937128922
Epoch 20/25, Loss: 0.9907383560357942
Epoch 21/25, Loss: 0.9271090918345928
Epoch 22/25, Loss: 0.8807898699635414
Epoch 23/25, Loss: 0.8481329700934788
Epoch 24/25, Loss: 0.825077603757543
Epoch 25/25, Loss: 0.8082949479712545


# Model Evalution

In [34]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5846414566040039
