In [2]:
import torch

In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
#using empty
a=torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
if torch.cuda.is_available():
  print("GPU is avaliable!")
  print(f"Using GPU {torch.cuda.get_device_name}")
else:
  print("GPU is not avaliable!")

GPU is avaliable!
Using GPU <function get_device_name at 0x7a62eb733ce0>


In [8]:
#using rand
torch.rand(2,3)

tensor([[0.9539, 0.6667, 0.6987],
        [0.4114, 0.7741, 0.8059]])

In [9]:
torch.manual_seed(50)
b=torch.rand(2,3)

In [10]:
b

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [11]:
b

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [12]:
#Using tensor
torch.tensor(([1,2,3],[4,5,5]))

tensor([[1, 2, 3],
        [4, 5, 5]])

In [13]:
#Using arrange
print(torch.arange(0,10,2))

# Using linspace
print(torch.linspace(0,10,5))

# Using Eye

print(torch.eye(5))

# using full
print(torch.full((3,3),5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


DATA TYPES

In [14]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.dtype

torch.int64

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Mathemetical Operarions

In [18]:
torch.tensor([[1,2,3],[4,5,6]],dtype=float)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [19]:
#Using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Matrix operations

In [20]:
f=torch.randint(0,10,(3,3))
g=torch.randint(0,11,(3,3))
print(f)
print(g)

tensor([[4, 0, 5],
        [4, 8, 7],
        [5, 0, 7]])
tensor([[8, 4, 2],
        [8, 7, 1],
        [0, 9, 2]])


In [21]:
#matrix multiplication
matmul=torch.matmul(f,g)
matmul

tensor([[ 32,  61,  18],
        [ 96, 135,  30],
        [ 40,  83,  24]])

In [22]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [23]:
torch.transpose(f,0,1)

tensor([[4, 4, 5],
        [0, 8, 0],
        [5, 7, 7]])

In [24]:
# determinent

h=torch.randint(size=(2,2),low=0,high=10,dtype=torch.float32)
torch.det(h)

tensor(22.)

In [25]:
torch.inverse(h)

tensor([[ 0.4091, -0.1818],
        [-0.3636,  0.2727]])

In [26]:
i=torch.randint(size=(2,2),low=0,high=10)
j=torch.randint(0,10,(2,2))
print(i)
print(j)

tensor([[9, 9],
        [1, 8]])
tensor([[3, 4],
        [2, 1]])


In [27]:
i>j

#checking lessthan
i<j

#equal
i==j

#not equal
i!=j
i>j
i>=j
i<=j

tensor([[False, False],
        [ True, False]])

Special Functions

In [28]:
k=torch.randint(0,10,(2,3),dtype=float)
torch.exp(k)

tensor([[5.4598e+01, 2.0086e+01, 2.9810e+03],
        [2.0086e+01, 1.0000e+00, 2.7183e+00]], dtype=torch.float64)

In [29]:
torch.log(k)

tensor([[1.3863, 1.0986, 2.0794],
        [1.0986,   -inf, 0.0000]], dtype=torch.float64)

In [30]:
k

tensor([[4., 3., 8.],
        [3., 0., 1.]], dtype=torch.float64)

In [31]:
torch.softmax(k,dim=1)# k should be in float

tensor([[0.0179, 0.0066, 0.9756],
        [0.8438, 0.0420, 0.1142]], dtype=torch.float64)

In [32]:
torch.relu(k)## Relu should be work in float as well as int


tensor([[4., 3., 8.],
        [3., 0., 1.]], dtype=torch.float64)

Inplace ops

In [33]:
l=torch.rand(2,2)
print(l)
m=torch.rand(2,2)
print(m)

tensor([[0.1705, 0.2914],
        [0.5682, 0.0380]])
tensor([[0.2715, 0.6987],
        [0.0944, 0.6719]])


In [34]:
torch.relu(l)

tensor([[0.1705, 0.2914],
        [0.5682, 0.0380]])

In [35]:
torch.relu(m)

tensor([[0.2715, 0.6987],
        [0.0944, 0.6719]])

In [36]:
l.add(m)

tensor([[0.4420, 0.9901],
        [0.6627, 0.7099]])

Copying a tensor

In [37]:
a=torch.randint(size=(3,3),low=0,high=10)
a

tensor([[7, 0, 6],
        [2, 2, 1],
        [8, 3, 1]])

Tensor Operations

In [38]:
torch.cuda.is_available()

True

In [39]:
device=torch.device('cuda')

In [40]:
torch.rand((2,3),device=device)

tensor([[0.3146, 0.1458, 0.3482],
        [0.9447, 0.1015, 0.8101]], device='cuda:0')

In [41]:
#convering the existing tensor into gpu tensor
b=torch.rand((2,3))
b

tensor([[0.3880, 0.1319, 0.5018],
        [0.8077, 0.9322, 0.5680]])

In [42]:
a=b.to(device)
a

tensor([[0.3880, 0.1319, 0.5018],
        [0.8077, 0.9322, 0.5680]], device='cuda:0')

Checking the Time differnce between the tensors

In [48]:
import time
mat1=torch.rand((1000,1000))
mat2=torch.rand((1000,1000))

start_time=time.time()
result_cpu=torch.matmul(mat1,mat2)
cpu_time=time.time()-start_time
print(f"CPU time: {cpu_time:.4f}")

matgpu1=mat1.to('cuda')
matgpu2=mat2.to('cuda')

start_time=time.time()
result_gpu=torch.matmul(matgpu1,matgpu2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time
print(f"Gpu time:{gpu_time:.4f}")

CPU time: 0.0645
Gpu time:0.0048
