Autograd:

Its a core component of pytorch that provides automatic differntiaton for tensor Operations

In [3]:
import torch

Basic differntial math


In [ ]:
def dy_dx(x):
  return x**2

In [ ]:
dy_dx(3)

9

In [ ]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2

In [ ]:
x

tensor(3., requires_grad=True)

Here y showing power backward that means it is performing backward operations or derivatives

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

Lets check with another example of dz_dx.

In [ ]:
import math
def dz_dx(x):
  return 2*x*math.cos(x**2)

In [ ]:
dz_dx(4)

-7.661275842587077

Now lets try with autograd by taking x as tensor

In [ ]:
x=torch.tensor(4.0,requires_grad=True)
y=x**2
z=torch.sin(y)

In [ ]:
x

tensor(4., requires_grad=True)

In [ ]:
y

tensor(16., grad_fn=<PowBackward0>)

For knowing the Z value. It performs sine backward opearion.

In [ ]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

grad is only accesssible to root node and doesnot for leaf nodes

In [ ]:
x.grad

tensor(-7.6613)

In [ ]:
z.grad

/tmp/ipython-input-4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  z.grad


In [5]:
def binary_cross_entropy_loss(y_pred,y):
  return -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred))

In [8]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [9]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [10]:
w

tensor(1., requires_grad=True)

In [11]:
b

tensor(0., requires_grad=True)

In [12]:
z=w*x+b

In [13]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [14]:
y_pred=torch.sigmoid(z)

In [15]:
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [16]:
loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [18]:
loss.backward()

In [19]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [25]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [26]:
x

tensor([1., 2., 3.], requires_grad=True)

In [27]:
y=(x**2).mean()

In [28]:
y.backward()

In [30]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [49]:
a=torch.tensor(2.0,requires_grad=True)
a

tensor(2., requires_grad=True)

In [50]:
y=a**2

In [51]:
y

tensor(4., grad_fn=<PowBackward0>)

In [52]:
y.backward()

In [53]:
a.grad

tensor(4.)